- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - variables.yml
    - secrets.yml

  tasks:
    - name: launch EBS-backed instance
      ec2:
        image: '{{ source_ami }}'
        instance_type: '{{ instance_type }}'
        region: '{{ region }}'
        keypair: '{{ keypair }}'
        group: '{{ security_group }}'
        wait: true
        volumes: '{{ source_volumes }}'
      register: ec2

    - name: wait for SSH to come up
      wait_for: >
        host={{ ec2.instances.0.public_ip }}
        port=22
        delay=10
        timeout=120
        state=started

    - name: add instance public IP to host group
      add_host: >
        name={{ ec2.instances.0.public_ip }}
        groups=ec2
        ansible_ssh_user=root
